# Generated by Django 3.2.9 on 2022-01-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paymentuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=60)),
                ('cardname', models.CharField(max_length=90)),
                ('cardnumber', models.BigIntegerField()),
                ('expmonth', models.CharField(max_length=90)),
                ('expyear', models.IntegerField()),
                ('cvv', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='signupuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stfirstname', models.CharField(max_length=30)),
                ('stlastname', models.CharField(max_length=30)),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('stcity', models.CharField(max_length=30)),
                ('mo', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='usersuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('subject', models.TextField()),
                ('feedback', models.TextField()),
                ('nameofuploader', models.CharField(max_length=100)),
            ],
        ),
    ]
