# Generated by Django 3.2.9 on 2022-02-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teastall', '0003_signupuser_selectimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupuser',
            name='selectimages',
            field=models.FileField(blank=True, upload_to='Myimages'),
        ),
    ]
