# Generated by Django 3.2.9 on 2022-02-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teastall', '0004_alter_signupuser_selectimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupuser',
            name='gender',
            field=models.CharField(default='NA', max_length=15),
            preserve_default=False,
        ),
    ]
