# Generated by Django 3.2.9 on 2022-02-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teastall', '0005_signupuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupuser',
            name='cpassword',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
    ]
