# Generated by Django 3.2.9 on 2022-02-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teastall', '0006_signupuser_cpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuser',
            name='cuser',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signupuser',
            name='gender',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
