# Generated by Django 3.2.9 on 2022-02-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teastall', '0007_auto_20220207_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentuser',
            name='cpay',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
    ]
